<?php
/*
2. Escriba un programa que muestre una tirada de dado al azar y escriba en letras el valor
obtenido. Necesitáis la función rand
 */

$cara=rand(1,6);

switch ($cara){
    case 1:
        echo "Te ha tocado el número ".$cara;
        break;
    case 2:
        echo "Te ha tocado el número ".$cara;
        break;
    case 3:
        echo "Te ha tocado el número ".$cara;
        break;
    case 4:
        echo "Te ha tocado el número ".$cara;
        break;
    case 5:
        echo "Te ha tocado el número ".$cara;
        break;
    case 6:
        echo "Te ha tocado el número ".$cara;
        break;
        
}
?>